#!/usr/bin/env sh

/usr/libexec/PlistBuddy \
-c 'delete :MiniCustomized' \
~/Library/Preferences/com.apple.controlstrip.plist

/usr/libexec/PlistBuddy \
-c 'add :MiniCustomized array' \
-c 'add :MiniCustomized:0 string "com.apple.system.brightness"' \
-c 'add :MiniCustomized:1 string "com.apple.system.volume"' \
-c 'add :MiniCustomized:2 string "com.apple.system.search"' \
~/Library/Preferences/com.apple.controlstrip.plist
