#!/usr/bin/env sh

if [ ! -f ~/Library/Preferences/com.unity3d.UnityEditor5.x.plist ]; then
  open /Applications/Unity/Unity.app
  sleep 10
  killall Unity
fi

vscode="/Applications/Visual Studio Code.app"
if [ "$USE_VSCODE_INSIDERS" -eq "yes" ]; then
  vscode="/Applications/Visual Studio Code - Insiders.app"
fi

plutil -replace kScriptsDefaultApp -string "$vscode" ~/Library/Preferences/com.unity3d.UnityEditor5.x.plist

# Don't ask me why this requires so many escapes
vscodeEscaped=`echo $vscode | sed s/\.app/\\\\\\\.app/`
argsKey="kScriptEditorArgs_$vscodeEscaped"
plutil -replace "$argsKey" -string '' ~/Library/Preferences/com.unity3d.UnityEditor5.x.plist
