#!/usr/bin/env sh

HARDWARE_UUID="$(system_profiler SPHardwareDataType | awk '/UUID/ { print $3; }')"
TARGET="~/.dotfiles/Preferences/ByHost/.GlobalPreferences.$HARDWARE_UUID.plist"

if [ -f $TARGET ]; then
  rm $TARGET
fi

ln -s ~/.dotfiles/Preferences/ByHost/.GlobalPreferences.HARDWARE_UUID.plist ~/Library/Preferences/ByHost/.GlobalPreferences.$HARDWARE_UUID.plist

exit 0
