#!/usr/bin/env sh

USER_DESKTOP=~/.dotfiles/desktop.$(./dotfiles_user).png

if [ -f $USER_DESKTOP ]; then
  setwp --fill $USER_DESKTOP
fi

ADMIN_DESKTOP=~/.dotfiles/desktop.admin.$(./dotfiles_host).png
ADMIN_TARGET=/Library/Caches/com.apple.desktop.admin.png

if [ -f $ADMIN_DESKTOP ]; then
  if [ ! -L $ADMIN_TARGET ]; then
    sudo ln -sf $ADMIN_DESKTOP $ADMIN_TARGET
  fi
fi
