#!/usr/bin/env sh

mysides remove all

mysides add 'domain-AirDrop' 'nwnode://domain-AirDrop'
mysides add 'Macintosh HD' 'file:///'
mysides add 'Applications' 'file:///Applications/'
mysides add 'kibiyama' 'file:///Users/kibiyama/'
mysides add 'git' 'file:///Users/kibiyama/git/'
mysides add 'Desktop' 'file:///Users/kibiyama/Desktop/'
mysides add 'Documents' 'file:///Users/kibiyama/Documents/'
mysides add 'Downloads' 'file:///Users/kibiyama/Downloads/'
mysides add 'Dropbox' 'file:///Users/kibiyama/Dropbox/'
mysides add 'Dropbox (YETi CGI)' 'file:///Users/kibiyama/Dropbox%20(YETi%20CGI)/'

