#!/usr/bin/env sh

USER_DESKTOP=~/.dotfiles/desktop.$(./dotfiles_user).png

setwp --fill $USER_DESKTOP

ADMIN_DESKTOP=~/.dotfiles/desktop.admin.$(./dotfiles_host).png
ADMIN_TARGET=/Library/Caches/com.apple.desktop.admin.png

if [ ! -L $ADMIN_TARGET ]; then
  sudo rm $ADMIN_TARGET
  sudo ln -s $ADMIN_DESKTOP $ADMIN_TARGET
fi
