#!/usr/bin/env sh

USER_DESKTOP=~/.dotfiles/desktop.$(./dotfiles_user).png
if [ -f $USER_DESKTOP ]; then
  setwp --fill $USER_DESKTOP
fi

ADMIN_DESKTOP=~/.dotfiles/admin.desktop.$(./dotfiles_host).png
if [ -f $ADMIN_DESKTOP ]; then
  TARGET=/Library/Caches/com.apple.desktop.admin.png
  sudo rm $TARGET
  sudo ln -s $ADMIN_DESKTOP $TARGET
fi
