#!/usr/bin/env sh

if ! which mysides; then
  echo "mysides is not installed"
  exit 0
fi

mysides remove all

mysides add 'domain-AirDrop' 'nwnode://domain-AirDrop'
mysides add 'Macintosh HD' 'file:///'
mysides add 'Applications' 'file:///Applications/'
mysides add 'kibiyama' "file://$HOME/"
mysides add 'git' "file://$HOME/git/"
mysides add 'Desktop' "file://$HOME/Desktop/"
mysides add 'Documents' "file://$HOME/Documents/"
mysides add 'Downloads' "file://$HOME/Downloads/"
mysides add 'Dropbox' "file://$HOME/Dropbox/"
mysides add 'Dropbox (YETi CGI)' "file://$HOME/Dropbox%20(YETi%20CGI)/"

