#!/usr/bin/env sh

HARDWARE_UUID="$(system_profiler SPHardwareDataType | awk '/UUID/ { print $3; }')"
TARGET=~/Library/Preferences/ByHost/.GlobalPreferences.$HARDWARE_UUID.plist

if [ ! -L $TARGET ]; then
  rm $TARGET
  ln -s ~/.dotfiles/Preferences/ByHost/.GlobalPreferences.HARDWARE_UUID.plist $TARGET
fi

