#!/usr/bin/env sh

if [ ! -d  ~/Library/Application\ Support/Google/Chrome/Default ]; then
  open /Applications/Google\ Chrome.app
  sleep 10
  killall Google\ Chrome
fi

if [ ! -L ~/Library/Application\ Support/Google/Chrome/Default/Bookmarks ]; then
  rm ~/Library/Application\ Support/Google/Chrome/Default/Bookmarks
  ln -s ~/.dotfiles/Chrome/Bookmarks ~/Library/Application\ Support/Google/Chrome/Default/Bookmarks
fi

if [ ! -L ~/Library/Application\ Support/Google/Chrome/Default/Preferences ]; then
  rm ~/Library/Application\ Support/Google/Chrome/Default/Preferences
  ln -s ~/.dotfiles/Chrome/Preferences ~/Library/Application\ Support/Google/Chrome/Default/Preferences
fi
