#!/usr/bin/env sh

os_version=`defaults read loginwindow SystemVersionStampAsString`
if echo $os_version | grep 10.12; then
  nohup mas install 497799835 #Xcode
else
  echo "Since your OS version is $os_version, I'll assume you can't install the latest Xcode (it requires Sierra or above)"
fi

nohup mas install \
443987910 `#1Password` \
425424353 `# The Unarchiver` \
407951449 `# Things` \
803453959 `# Slack` \
407963104 `# Pixelmator` \
447661441 `# xScope` \
417375580 `# BetterSnapTool` \
411643860 `# DaisyDisk` &>/dev/null &
