#!/usr/bin/env sh

if [ -d /Applications/MacVim.app ]; then
  echo "MacVim already installed"
else
  curl -Lo MacVim.dmg https://github.com/macvim-dev/macvim/releases/download/snapshot-136/MacVim.dmg
  hdiutil attach MacVim.dmg
  cp -r /Volumes/MacVim/MacVim.app /Applications/MacVim.app
  hdiutil detach /Volumes/MacVim
fi

# TODO: Set non-native fullscreen; this is not enough to get it to init the plist
# if [ ! -f ~/Library/Preferences/org.vim.MacVim.plist ]; then
#   open /Applications/MacVim.app
#   sleep 10
#   killall MacVim
# fi
#
# plutil -replace MMNativeFullScreen -int 0 ~/Library/Preferences/org.vim.MacVim.plist
