#!/usr/bin/env sh

if which dotnet; then
  echo ".NET SDK already installed"
  exit 0
fi

OS_VERSION=`defaults read loginwindow SystemVersionStampAsString`

if echo $OS_VERSION | grep -e "10.1[2-9]" > /dev/null; then
  brew cask install dotnet-sdk
else
  echo "Since your OS version is $OS_VERSION, I'll assume you can't install the .NET SDK (it requires Sierra or above)"
fi
