#!/usr/bin/env ruby

app_path =
  if ENV["USE_SUDO"]
    "/Applications"
  else
    "#{ENV["HOME"]}/Applications"
  end

if Dir.exists? "#{app_path}/iTerm.app"
  puts "iTerm2 already installed"
else
  system "curl -Lo iTerm2.zip https://iterm2.com/downloads/stable/latest"
  system "unzip -d #{app_path} iTerm2.zip"
end

# system "curl -L https://iterm2.com/misc/install_shell_integration_and_utilities.sh | bash"

system 'defaults write ~/Library/Preferences/com.googlecode.iterm2.plist PrefsCustomFolder -string "$HOME/.iTerm2"'
system 'defaults write ~/Library/Preferences/com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool YES'
