#!/usr/bin/env ruby

require "fileutils"

UseBleedingEdge = ENV["USE_VSCODE_INSIDERS"]

app_path =
  if ENV["USE_HOME_APPDIR"]
    "#{ENV["HOME"]}/Applications"
  else
    "/Applications"
  end

zip_app_path = 
  if UseBleedingEdge
    "Visual Studio Code - Insiders.app"
  else
    "Visual Studio Code.app"
  end

default_vscode_dir = "#{app_path}/#{zip_app_path}"
target_vscode_dir = "#{app_path}/Visual Studio Code.app"

link_id =
  if UseBleedingEdge
    "723966"
  else
    "620882"
  end

if UseBleedingEdge
  puts "Using bleeding edge VSCode"
end

puts app_path

if Dir.exists? target_vscode_dir
  puts "VSCode already installed; reinstalling"
  FileUtils.rm_rf target_vscode_dir
end

system "curl -Lo vscode.zip https://go.microsoft.com/fwlink/?LinkId=#{link_id}"

system "unzip vscode.zip '#{zip_app_path}/*' -d '#{app_path}'"

FileUtils.mv default_vscode_dir, target_vscode_dir
