#!/usr/bin/env ruby

# Temporarily using bleeding edge until this is resolved:
# https://github.com/Microsoft/vscode/issues/32381
UseBleedingEdge = ENV["USE_VSCODE_INSIDERS"]

vscode_dir =
  if UseBleedingEdge
    "/Applications/Visual Studio Code - Insiders.app"
  else
    "/Applications/Visual Studio Code.app"
  end

if Dir.exists? vscode_dir
  puts "VSCode#{if UseBleedingEdge then " Bleeding Edge" else "" end} already installed"
else
  if UseBleedingEdge
    system "curl -Lo vscode.zip https://go.microsoft.com/fwlink/?LinkId=723966"
  else
    system "curl -Lo vscode.zip https://go.microsoft.com/fwlink/?LinkID=620882"
  end
  system "unzip -d /Applications vscode.zip"
end
