#!/usr/bin/env sh

os_version=`defaults read loginwindow SystemVersionStampAsString`
if echo $os_version | grep 10.12; then
  brew cask install dotnet-sdk
else
  echo "Since your OS version is $os_version, I'll assume you can't install the .NET SDK (it requires Sierra or above)"
fi
