#!/usr/bin/env sh

OS_VERSION=$(./os_version)
if [ "$OS_VERSION" -ge 12 ]; then
  if [ ! -d /Application/Xcode.app ]; then
    nohup mas install 497799835 &>/dev/null &
  fi
else
  echo "Since your OS version is $OS_VERSION, I'll assume you can't install the latest Xcode (it requires Sierra or above)"
fi

nohup mas install \
443987910 `# 1Password` \
425424353 `# The Unarchiver` \
407951449 `# Things` \
803453959 `# Slack` \
407963104 `# Pixelmator` \
447661441 `# xScope` \
417375580 `# BetterSnapTool` \
446107677 `# Screens` \
411643860 `# DaisyDisk` &>/dev/null &
