#!/usr/bin/env sh

/Applications/Visual\ Studio\ Code*.app/Contents/Resources/app/bin/code \
    --install-extension Ionide.ionide-fake \
    --install-extension Ionide.ionide-fsharp \
    --install-extension Unity.unity-debug \
    --install-extension donjayamanne.githistory \
    --install-extension geddski.macros \
    --install-extension k--kato.docomment \
    --install-extension ms-vscode.cpptools \
    --install-extension ms-vscode.csharp \
    --install-extension ms-vscode.mono-debug \
    --install-extension redhat.java \
    --install-extension robertohuertasm.vscode-icons \
    --install-extension twxs.cmake \
    --install-extension vector-of-bool.cmake-tools \
    --install-extension vscjava.vscode-java-debug \
    --install-extension vscjava.vscode-java-pack \
    --install-extension vscjava.vscode-java-test \
    --install-extension vscjava.vscode-maven \
    --install-extension vscodevim.vim
