#!/usr/bin/env sh

APPDIR="/Applications"
if [ ! -z "$USE_HOME_APPDIR" ]; then
  APPDIR="$HOME/Applications"
fi

OS_VERSION=$(./os_version)
if [ "$OS_VERSION" -lt 12 ]; then
  echo "OS version $OS_VERSION too low for Mute Me"
  exit 0
fi

if [ -d "$APPDIR/Mute Me.app" ]; then
  echo "Mute Me already installed"
  exit 0
fi

curl -Lo mute-me.zip https://github.com/pixel-point/mute-me/releases/download/v1.2.0/mute-me-v1.2.0.zip

unzip mute-me.zip "Mute Me.app/*" -d "$APPDIR"

open "$APPDIR/Mute Me.app"
