#!/usr/bin/env bash

rm -rf hackintosh/kexts
mkdir hackintosh/kexts

files=$(ls hackintosh/Lilu-and-Friends/Kexts/*.zip)

IFS=$'\n'

for file in $files; do
  unzip -d hackintosh/kexts "$file"
done

mv hackintosh/kexts/VirtualSMC/Kexts/VirtualSMC.kext hackintosh/kexts/.
rm -rf hackintosh/kexts/VirtualSMC

disks=$(diskutil list | grep /dev/disk | sed 's/\/dev\/\(disk[[:digit:]]\).*/\1/')

cruzer=""

for disk in $disks; do
  if diskutil info $disk | grep "Device / Media Name:      Cruzer Glide" > /dev/null; then
    cruzer=$disk
  fi
done

if [[ -z $cruzer ]]; then
  echo "Couldn't find Cruzer Glide"
  exit 1
fi

echo "Found Cruzer Glide at $cruzer"

sudo mkdir /Volumes/ESP
sudo mount -t msdos /dev/"$cruzer"s1 /Volumes/ESP

rm -rf /Volumes/ESP/EFI/CLOVER/kexts/Other/*
cp -r hackintosh/kexts/*.kext /Volumes/ESP/EFI/CLOVER/kexts/Other
