#!/usr/bin/env bash

hackintosh/mount_usb

rm -rf hackintosh/kexts
mkdir hackintosh/kexts

files=$(ls hackintosh/Lilu-and-Friends/Kexts/*.zip)

IFS=$'\n'

for file in $files; do
  unzip -d hackintosh/kexts "$file"
done

mv hackintosh/kexts/VirtualSMC/Kexts/VirtualSMC.kext hackintosh/kexts/.
rm -rf hackintosh/kexts/VirtualSMC

rm -rf /Volumes/ESP-USB/EFI/CLOVER/kexts/Other/*
cp -r hackintosh/kexts/*.kext /Volumes/ESP-USB/EFI/CLOVER/kexts/Other

