#!/usr/bin/env bash

disks=$(diskutil list | grep /dev/disk | sed 's/\/dev\/\(disk[[:digit:]]\).*/\1/')

cruzer=""

for disk in $disks; do
  if diskutil info $disk | grep "Device / Media Name:      Cruzer Glide" > /dev/null; then
    cruzer=$disk
  fi
done

if [[ -z $cruzer ]]; then
  echo "Couldn't find Cruzer Glide"
  exit 1
fi

echo "Found Cruzer Glide at $cruzer"

sudo mkdir /Volumes/ESP
sudo mount -t msdos /dev/"$cruzer"s1 /Volumes/ESP

echo <<-EOS > /Volumes/ESP/EFI/CLOVER/switch_to_internal_config
#!/usr/bin/env bash

disks=$(diskutil list | grep /dev/disk | sed 's/\/dev\/\(disk[[:digit:]]\).*/\1/')

cruzer=""

for disk in $disks; do
  if diskutil info $disk | grep "Device / Media Name:      Cruzer Glide" > /dev/null; then
    cruzer=$disk
  fi
done

if [[ -z $cruzer ]]; then
  echo "Couldn't find Cruzer Glide"
  exit 1
fi

echo "Found Cruzer Glide at $cruzer"

sudo mkdir /Volumes/ESP
sudo mount -t msdos /dev/disk0s1 /Volumes/ESP

sudo mkdir /Volumes/ESP2
sudo mount -t msdos /dev/"$cruzer"s1 /Volumes/ESP2

rm -rf /Volumes/ESP/EFI
cp -r /Volumes/ESP2/EFI /Volumes/ESP/EFI

mv /Volumes/ESP/EFI/CLOVER/internal_config.plist /Volumes/ESP/EFI/CLOVER/config.plist
EOS

chmod +x /Volumes/ESP/EFI/CLOVER/switch_to_internal_config

