#!/usr/bin/env bash

if [ ! -f hackintosh/clover.pkg ]; then
  curl -Lo hackintosh/clover.pkg https://github.com/Dids/clover-builder/releases/download/v2.4k_r4846/Clover_v2.4k_r4846.pkg
fi

sudo installer -applyChoiceChangesXML hackintosh/install_clover.plist -package hackintosh/clover.pkg -target /

