#!/usr/bin/env bash

disks=$(diskutil list | grep /dev/disk | sed 's/\/dev\/\(disk[[:digit:]]\).*/\1/')

cruzer=""

for disk in $disks; do
  if diskutil info $disk | grep "Device / Media Name:      Cruzer Glide" > /dev/null; then
    cruzer=$disk
  fi
done

if [[ -z $cruzer ]]; then
  echo "Couldn't find Cruzer Glide"
  exit 1
fi

echo "Found Cruzer Glide at $cruzer"

diskutil partitionDisk $cruzer GPT JHFS+ USB 30G JHFS+ Untitled R

sudo "/Applications/Install macOS Mojave.app/Contents/Resources/createinstallmedia" --volume /Volumes/USB --nointeraction

hackintosh/install_clover

hackintosh/copy_kexts

hackintosh/copy_themes

hackintosh/copy_config
