#!/usr/bin/env bash

sudo diskutil unmount /Volumes/ESP

disks=$(diskutil list | grep /dev/disk | sed 's/\/dev\/\(disk[[:digit:]]\).*/\1/')

cruzer=""

for disk in $disks; do
  if diskutil info $disk | grep "Cruzer Glide" > /dev/null; then
    cruzer=$disk
  fi
done

if [[ -z $cruzer ]]; then
  echo "Couldn't find Cruzer Glide"
  exit 1
fi

echo "Found Cruzer Glide at $cruzer"

sudo mkdir /Volumes/ESP
sudo mount -t msdos /dev/"$cruzer"s1 /Volumes/ESP

